export type Period = 'weekly'|'monthly'|'quarterly'|'annual';
export interface Requirement {period:Period; kind:'minutes'|'sessions'; amount:number}
export interface Student {id:string;name:string;school:string;grade:string;deadline:string;requirement:Requirement;goal:string}
export interface Session {id:string;date:string;time:string;duration:number;studentIds:string[];focus:string}
export interface Log {id:string;sessionId?:string;date:string;studentId:string;minutes:number;notes:string}
export type Availability = Record<string,'available'|'unavailable'|'discouraged'>;
export interface Data {students:Student[];sessions:Session[];logs:Log[];availability:Availability}
export const schools=['Maple Grove Elementary','Willow Creek Elementary','Oak Meadow Elementary','Cedar Hill Elementary','Pine Ridge Elementary'];
export function dateKey(date:Date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
export function localDate(key:string){const [y,m,d]=key.split('-').map(Number);return new Date(y,m-1,d);}
export function monday(date:Date){const d=new Date(date);d.setHours(0,0,0,0);d.setDate(d.getDate()-((d.getDay()+6)%7));return d;}
export function periodBounds(period:Period,asOf:Date):[string,string]{let start=new Date(asOf.getFullYear(),asOf.getMonth(),1);let end:Date;
 if(period==='weekly'){start=monday(asOf);end=new Date(start);end.setDate(end.getDate()+7);}else if(period==='monthly'){end=new Date(start.getFullYear(),start.getMonth()+1,1);}else if(period==='quarterly'){start=new Date(asOf.getFullYear(),Math.floor(asOf.getMonth()/3)*3,1);end=new Date(start.getFullYear(),start.getMonth()+3,1);}else{start=new Date(asOf.getFullYear(),0,1);end=new Date(asOf.getFullYear()+1,0,1);}return [dateKey(start),dateKey(end)];}
export function progress(student:Student,logs:Log[],asOf:Date){const [start,end]=periodBounds(student.requirement.period,asOf);const matches=logs.filter(l=>l.studentId===student.id&&l.date>=start&&l.date<end);const actual=student.requirement.kind==='minutes'?matches.reduce((n,l)=>n+l.minutes,0):new Set(matches.map(l=>l.sessionId || l.id)).size;return {actual,target:student.requirement.amount,remaining:Math.max(0,student.requirement.amount-actual),percent:Math.min(100,actual/student.requirement.amount*100)};}
export function seed():Data {const first=['Avery','Jordan','Riley','Morgan','Cameron','Quinn','Taylor','Parker','Rowan','Skyler'];const last=['Bennett','Ellis','Hayes','Reed','Brooks','Foster','Lane','Sullivan','Carter','Wells'];const today=new Date();const week=monday(today);const students:Student[]=Array.from({length:100},(_,i)=>{const deadline=new Date(today);deadline.setDate(deadline.getDate()+7+i*2);const period:Period=(['weekly','monthly','quarterly','annual'] as Period[])[i%4];const kind=i%9===0?'sessions':'minutes';return {id:`s${i+1}`,name:`${first[i%10]} ${last[Math.floor(i/10)]}`,school:schools[Math.floor(i/20)],grade:['K','1','2','3','4','5'][i%6],deadline:dateKey(deadline),requirement:{period,kind,amount:kind==='sessions'?({weekly:2,monthly:4,quarterly:12,annual:36}[period]):({weekly:30,monthly:120,quarterly:360,annual:1440}[period])},goal:['Fine motor & handwriting','Sensory regulation','Visual motor integration','Classroom participation'][i%4]};});const sessions:Session[]=Array.from({length:25},(_,i)=>{const day=new Date(week);day.setDate(day.getDate()+Math.floor(i/5));const base=Math.floor(i/5)*20+i%5*3;return {id:`session${i}`,date:dateKey(day),time:['09:00','10:00','11:00','13:00','14:00'][i%5],duration:30,studentIds:i%2===0?[students[base].id]:students.slice(base,base+3).map(s=>s.id),focus:students[base].goal};});const logs:Log[]=sessions.filter(s=>s.date<dateKey(today)).flatMap(s=>s.studentIds.map(studentId=>({id:`demo-${s.id}-${studentId}`,sessionId:s.id,date:s.date,studentId,minutes:30,notes:'Fictional sample session.'})));return {students,sessions,logs,availability:{}};}
